//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.WebApi.Models
{
    /// <summary>
    /// This part of the class contains the derivation for the 'VersionEntityObject'.
    /// </summary>
    partial class VersionEntityObject : ModelObject
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static VersionEntityObject Create()
        {
            BeforeCreate();
            var result = new VersionEntityObject();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(programming_trainer.WebApi.Models.VersionEntityObject model);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public static programming_trainer.WebApi.Models.VersionEntityObject Create(programming_trainer.Logic.Entities.VersionEntityObject entity)
        {
            var handled = false;
            var result = default(programming_trainer.WebApi.Models.VersionEntityObject);
            BeforeCreate(entity, ref result, ref handled);
            if (handled == false || result is null)
            {
                var visitedEntities = new List<object> { entity };
                result = new programming_trainer.WebApi.Models.VersionEntityObject();
                (result as programming_trainer.Common.Contracts.IVersionEntityObject).CopyProperties(entity);
            }
            AfterCreate(entity, result);
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        internal static programming_trainer.WebApi.Models.VersionEntityObject? Create(List<object> visitedEntities, programming_trainer.Logic.Entities.VersionEntityObject entity)
        {
            var result = default(programming_trainer.WebApi.Models.VersionEntityObject);
            if (visitedEntities.Contains(entity) == false)
            {
                visitedEntities.Add(entity);
                result = new programming_trainer.WebApi.Models.VersionEntityObject();
                (result as programming_trainer.Common.Contracts.IVersionEntityObject).CopyProperties(entity);
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate(programming_trainer.Logic.Entities.VersionEntityObject entity, ref programming_trainer.WebApi.Models.VersionEntityObject? model, ref bool handled);
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(programming_trainer.Logic.Entities.VersionEntityObject entity, programming_trainer.WebApi.Models.VersionEntityObject model);
    }
}
