//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.MVVMApp.ViewModels.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class AssignmentViewModel : GenericItemViewModel<Models.App.Assignment>
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static AssignmentViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="AssignmentViewModel"/> class (created by the generator.)
        /// </summary>
        public AssignmentViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();

        /// <summary>
        /// Property 'StudentId' generated by the generator.
        /// </summary>
        public IdType StudentId
        {
            get
            {
                return Model.StudentId;
            }
            set
            {
                Model.StudentId = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'StudentPrompt' generated by the generator.
        /// </summary>
        public System.String StudentPrompt
        {
            get
            {
                return Model.StudentPrompt;
            }
            set
            {
                Model.StudentPrompt = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'CategoryId' generated by the generator.
        /// </summary>
        public IdType CategoryId
        {
            get
            {
                return Model.CategoryId;
            }
            set
            {
                Model.CategoryId = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title
        {
            get
            {
                return Model.Title;
            }
            set
            {
                Model.Title = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Description' generated by the generator.
        /// </summary>
        public System.String Description
        {
            get
            {
                return Model.Description;
            }
            set
            {
                Model.Description = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Status' generated by the generator.
        /// </summary>
        public System.String Status
        {
            get
            {
                return Model.Status;
            }
            set
            {
                Model.Status = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'CreatedDate' generated by the generator.
        /// </summary>
        public System.DateTime CreatedDate
        {
            get
            {
                return Model.CreatedDate;
            }
            set
            {
                Model.CreatedDate = value;
                OnPropertyChanged();
            }
        }
    }
}
