//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.MVVMApp.ViewModels.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class StudentResponseViewModel : GenericItemViewModel<Models.App.StudentResponse>
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static StudentResponseViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentResponseViewModel"/> class (created by the generator.)
        /// </summary>
        public StudentResponseViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();

        /// <summary>
        /// Property 'AssignmentId' generated by the generator.
        /// </summary>
        public IdType AssignmentId
        {
            get
            {
                return Model.AssignmentId;
            }
            set
            {
                Model.AssignmentId = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'SubmittedAnswer' generated by the generator.
        /// </summary>
        public System.String SubmittedAnswer
        {
            get
            {
                return Model.SubmittedAnswer;
            }
            set
            {
                Model.SubmittedAnswer = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Score' generated by the generator.
        /// </summary>
        public System.Int32 Score
        {
            get
            {
                return Model.Score;
            }
            set
            {
                Model.Score = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Feedback' generated by the generator.
        /// </summary>
        public System.String Feedback
        {
            get
            {
                return Model.Feedback;
            }
            set
            {
                Model.Feedback = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'SubmissionDate' generated by the generator.
        /// </summary>
        public System.DateTime SubmissionDate
        {
            get
            {
                return Model.SubmissionDate;
            }
            set
            {
                Model.SubmissionDate = value;
                OnPropertyChanged();
            }
        }
    }
}
