//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.MVVMApp.ViewModels.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class StudentViewModel : GenericItemViewModel<Models.App.Student>
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static StudentViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentViewModel"/> class (created by the generator.)
        /// </summary>
        public StudentViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();

        /// <summary>
        /// Property 'FirstName' generated by the generator.
        /// </summary>
        public System.String FirstName
        {
            get
            {
                return Model.FirstName;
            }
            set
            {
                Model.FirstName = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'LastName' generated by the generator.
        /// </summary>
        public System.String LastName
        {
            get
            {
                return Model.LastName;
            }
            set
            {
                Model.LastName = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Email' generated by the generator.
        /// </summary>
        public System.String Email
        {
            get
            {
                return Model.Email;
            }
            set
            {
                Model.Email = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'StudentNumber' generated by the generator.
        /// </summary>
        public System.String StudentNumber
        {
            get
            {
                return Model.StudentNumber;
            }
            set
            {
                Model.StudentNumber = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'RegistrationDate' generated by the generator.
        /// </summary>
        public System.DateTime RegistrationDate
        {
            get
            {
                return Model.RegistrationDate;
            }
            set
            {
                Model.RegistrationDate = value;
                OnPropertyChanged();
            }
        }
    }
}
