//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.WebApi.Models.App
{
    /// <summary>
    /// This part of the class contains the derivation for the 'Assignment'.
    /// </summary>
    partial class Assignment : ModelObject
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static Assignment Create()
        {
            BeforeCreate();
            var result = new Assignment();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(programming_trainer.WebApi.Models.App.Assignment model);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public static programming_trainer.WebApi.Models.App.Assignment Create(programming_trainer.Logic.Entities.App.Assignment entity)
        {
            var handled = false;
            var result = default(programming_trainer.WebApi.Models.App.Assignment);
            BeforeCreate(entity, ref result, ref handled);
            if (handled == false || result is null)
            {
                var visitedEntities = new List<object> { entity };
                result = new programming_trainer.WebApi.Models.App.Assignment();
                (result as programming_trainer.Common.Contracts.App.IAssignment).CopyProperties(entity);
                if (entity.Student is not null)
                {
                    result.Student = programming_trainer.WebApi.Models.App.Student.Create(visitedEntities, entity.Student);
                }
                if (entity.Category is not null)
                {
                    result.Category = programming_trainer.WebApi.Models.Data.Category.Create(visitedEntities, entity.Category);
                }
                if (entity.StudentResponses is not null)
                {
                    foreach (var item in entity.StudentResponses)
                    {
                        var listItem = programming_trainer.WebApi.Models.App.StudentResponse.Create(visitedEntities, item);
                        if (listItem is not null)
                        {
                            result.StudentResponses.Add(listItem);
                        }
                    }
                }
            }
            AfterCreate(entity, result);
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        internal static programming_trainer.WebApi.Models.App.Assignment? Create(List<object> visitedEntities, programming_trainer.Logic.Entities.App.Assignment entity)
        {
            var result = default(programming_trainer.WebApi.Models.App.Assignment);
            if (visitedEntities.Contains(entity) == false)
            {
                visitedEntities.Add(entity);
                result = new programming_trainer.WebApi.Models.App.Assignment();
                (result as programming_trainer.Common.Contracts.App.IAssignment).CopyProperties(entity);
                if (entity.Student is not null)
                {
                    result.Student = programming_trainer.WebApi.Models.App.Student.Create(visitedEntities, entity.Student);
                }
                if (entity.Category is not null)
                {
                    result.Category = programming_trainer.WebApi.Models.Data.Category.Create(visitedEntities, entity.Category);
                }
                if (entity.StudentResponses is not null)
                {
                    foreach (var item in entity.StudentResponses)
                    {
                        var listItem = programming_trainer.WebApi.Models.App.StudentResponse.Create(visitedEntities, item);
                        if (listItem is not null)
                        {
                            result.StudentResponses.Add(listItem);
                        }
                    }
                }
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate(programming_trainer.Logic.Entities.App.Assignment entity, ref programming_trainer.WebApi.Models.App.Assignment? model, ref bool handled);
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(programming_trainer.Logic.Entities.App.Assignment entity, programming_trainer.WebApi.Models.App.Assignment model);
    }
}
