//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.WebApi.Models.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class AssignmentEdit
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static AssignmentEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="AssignmentEdit"/> class (created by the generator.)
        /// </summary>
        public AssignmentEdit()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'StudentId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'StudentId' generated by the generator.
        /// </summary>
        public IdType StudentId { get; set; }
        /// <summary>
        /// Property 'StudentPrompt' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'StudentPrompt' generated by the generator.
        /// </summary>
        public System.String StudentPrompt { get; set; } = string.Empty;
        /// <summary>
        /// Property 'CategoryId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'CategoryId' generated by the generator.
        /// </summary>
        public IdType CategoryId { get; set; }
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Title' generated by the generator.
        /// </summary>
        public System.String Title { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Description' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Description' generated by the generator.
        /// </summary>
        public System.String Description { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Status' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Status' generated by the generator.
        /// </summary>
        public System.String Status { get; set; } = string.Empty;
        /// <summary>
        /// Property 'CreatedDate' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'CreatedDate' generated by the generator.
        /// </summary>
        public System.DateTime CreatedDate { get; set; }
        /// <summary>
        /// Property 'Student' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Student' generated by the generator.
        /// </summary>
        public programming_trainer.WebApi.Models.App.Student? Student { get; set; }
        /// <summary>
        /// Property 'Category' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Category' generated by the generator.
        /// </summary>
        public programming_trainer.WebApi.Models.Data.Category? Category { get; set; }
    }
}
