//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.WebApi.Models.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class StudentResponseEdit
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static StudentResponseEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentResponseEdit"/> class (created by the generator.)
        /// </summary>
        public StudentResponseEdit()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'AssignmentId' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'AssignmentId' generated by the generator.
        /// </summary>
        public IdType AssignmentId { get; set; }
        /// <summary>
        /// Property 'SubmittedAnswer' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'SubmittedAnswer' generated by the generator.
        /// </summary>
        public System.String SubmittedAnswer { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Score' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Score' generated by the generator.
        /// </summary>
        public System.Int32 Score { get; set; }
        /// <summary>
        /// Property 'Feedback' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Feedback' generated by the generator.
        /// </summary>
        public System.String Feedback { get; set; } = string.Empty;
        /// <summary>
        /// Property 'SubmissionDate' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'SubmissionDate' generated by the generator.
        /// </summary>
        public System.DateTime SubmissionDate { get; set; }
        /// <summary>
        /// Property 'Assignment' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Assignment' generated by the generator.
        /// </summary>
        public programming_trainer.WebApi.Models.App.Assignment? Assignment { get; set; }
    }
}
