//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.WebApi.Models.App
{
    /// <summary>
    /// This part of the class contains the derivation for the 'Student'.
    /// </summary>
    partial class Student : ModelObject
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        public static Student Create()
        {
            BeforeCreate();
            var result = new Student();
            AfterCreate(result);
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate();
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(programming_trainer.WebApi.Models.App.Student model);
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public static programming_trainer.WebApi.Models.App.Student Create(programming_trainer.Logic.Entities.App.Student entity)
        {
            var handled = false;
            var result = default(programming_trainer.WebApi.Models.App.Student);
            BeforeCreate(entity, ref result, ref handled);
            if (handled == false || result is null)
            {
                var visitedEntities = new List<object> { entity };
                result = new programming_trainer.WebApi.Models.App.Student();
                (result as programming_trainer.Common.Contracts.App.IStudent).CopyProperties(entity);
                if (entity.Assignments is not null)
                {
                    foreach (var item in entity.Assignments)
                    {
                        var listItem = programming_trainer.WebApi.Models.App.Assignment.Create(visitedEntities, item);
                        if (listItem is not null)
                        {
                            result.Assignments.Add(listItem);
                        }
                    }
                }
            }
            AfterCreate(entity, result);
            return result;
        }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        internal static programming_trainer.WebApi.Models.App.Student? Create(List<object> visitedEntities, programming_trainer.Logic.Entities.App.Student entity)
        {
            var result = default(programming_trainer.WebApi.Models.App.Student);
            if (visitedEntities.Contains(entity) == false)
            {
                visitedEntities.Add(entity);
                result = new programming_trainer.WebApi.Models.App.Student();
                (result as programming_trainer.Common.Contracts.App.IStudent).CopyProperties(entity);
                if (entity.Assignments is not null)
                {
                    foreach (var item in entity.Assignments)
                    {
                        var listItem = programming_trainer.WebApi.Models.App.Assignment.Create(visitedEntities, item);
                        if (listItem is not null)
                        {
                            result.Assignments.Add(listItem);
                        }
                    }
                }
            }
            return result;
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void BeforeCreate(programming_trainer.Logic.Entities.App.Student entity, ref programming_trainer.WebApi.Models.App.Student? model, ref bool handled);
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void AfterCreate(programming_trainer.Logic.Entities.App.Student entity, programming_trainer.WebApi.Models.App.Student model);
    }
}
