//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.WebApi.Models.App
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class StudentEdit
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static StudentEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentEdit"/> class (created by the generator.)
        /// </summary>
        public StudentEdit()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'FirstName' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'FirstName' generated by the generator.
        /// </summary>
        public System.String FirstName { get; set; } = string.Empty;
        /// <summary>
        /// Property 'LastName' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'LastName' generated by the generator.
        /// </summary>
        public System.String LastName { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Email' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'Email' generated by the generator.
        /// </summary>
        public System.String Email { get; set; } = string.Empty;
        /// <summary>
        /// Property 'StudentNumber' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'StudentNumber' generated by the generator.
        /// </summary>
        public System.String StudentNumber { get; set; } = string.Empty;
        /// <summary>
        /// Property 'RegistrationDate' generated by the generator.
        /// </summary>
        /// <summary>
        /// Property 'RegistrationDate' generated by the generator.
        /// </summary>
        public System.DateTime RegistrationDate { get; set; }
    }
}
