//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.MVVMApp.Models.App
{
    using System;
    /// <summary>
    /// This model represents a transmission model for the 'StudentResponse' data unit.
    /// </summary>

    public partial class StudentResponse : programming_trainer.Common.Contracts.App.IStudentResponse
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static StudentResponse()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentResponse"/> class (created by the generator.)
        /// </summary>
        public StudentResponse()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called after the object has been initialized.
        /// </summary>
        partial void Constructed();
        /// <summary>
        /// Property 'AssignmentId' generated by the generator.
        /// </summary>
        public IdType AssignmentId { get; set; }
        /// <summary>
        /// Property 'SubmittedAnswer' generated by the generator.
        /// </summary>
        public System.String SubmittedAnswer { get; set; } = string.Empty;
        /// <summary>
        /// Property 'Score' generated by the generator.
        /// </summary>
        public System.Int32 Score { get; set; }
        /// <summary>
        /// Property 'Feedback' generated by the generator.
        /// </summary>
        public System.String Feedback { get; set; } = string.Empty;
        /// <summary>
        /// Property 'SubmissionDate' generated by the generator.
        /// </summary>
        public System.DateTime SubmissionDate { get; set; }
        /// <summary>
        /// Property 'Assignment' generated by the generator.
        /// </summary>
        public programming_trainer.MVVMApp.Models.App.Assignment? Assignment { get; set; }
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        /// <param name="obj">The object to compare with the current object.</param>
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.StudentResponse other)
            {
                result = base.Equals(other) && AssignmentId == other.AssignmentId
                    && IsEqualsWith(SubmittedAnswer, other.SubmittedAnswer)
                    && Score == other.Score
                    && IsEqualsWith(Feedback, other.Feedback)
                    && SubmissionDate == other.SubmissionDate;
            }
            return result;
        }
        /// <summary>
        /// Serves as the default hash function.
        /// </summary>
        public override int GetHashCode()
        {
            return this.CalculateHashCode(base.GetHashCode(), AssignmentId, SubmittedAnswer, Score, Feedback, SubmissionDate);
        }
    }
}
