//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace programming_trainer.Logic.DataContext
{
    /// <summary>
    /// Generated by the generator
    /// </summary>
    partial class ProjectDbContext
    {
        #region properties
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.Data.Category> DbCategorySet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.Data.ICategorySet CategorySet => (Contracts.Data.ICategorySet)GetEntitySet<Entities.Data.Category>();
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.Data.ProgrammingLanguage> DbProgrammingLanguageSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.Data.IProgrammingLanguageSet ProgrammingLanguageSet => (Contracts.Data.IProgrammingLanguageSet)GetEntitySet<Entities.Data.ProgrammingLanguage>();
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.App.Assignment> DbAssignmentSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.App.IAssignmentSet AssignmentSet => (Contracts.App.IAssignmentSet)GetEntitySet<Entities.App.Assignment>();
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.App.Student> DbStudentSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.App.IStudentSet StudentSet => (Contracts.App.IStudentSet)GetEntitySet<Entities.App.Student>();
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        private DbSet<Entities.App.StudentResponse> DbStudentResponseSet { get; set; }
        /// <summary>
        /// Generated by the generator.
        /// </summary>
        public Contracts.App.IStudentResponseSet StudentResponseSet => (Contracts.App.IStudentResponseSet)GetEntitySet<Entities.App.StudentResponse>();
        #endregion properties

        #region partial methods
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.DbObject
        {
            if (typeof(E) == typeof(Entities.Data.Category))
            {
                dbSet = DbCategorySet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Data.ProgrammingLanguage))
            {
                dbSet = DbProgrammingLanguageSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.Assignment))
            {
                dbSet = DbAssignmentSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.Student))
            {
                dbSet = DbStudentSet as DbSet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.StudentResponse))
            {
                dbSet = DbStudentResponseSet as DbSet<E>;
                handled = true;
            }
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorEntitySet<E>(ref EntitySet<E>? entitySet, ref bool handled) where E : Entities.EntityObject, new()
        {
            if (typeof(E) == typeof(Entities.Data.Category))
            {
                entitySet = new DataContext.Data.CategorySet(this, DbCategorySet) as EntitySet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.Data.ProgrammingLanguage))
            {
                entitySet = new DataContext.Data.ProgrammingLanguageSet(this, DbProgrammingLanguageSet) as EntitySet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.Assignment))
            {
                entitySet = new DataContext.App.AssignmentSet(this, DbAssignmentSet) as EntitySet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.Student))
            {
                entitySet = new DataContext.App.StudentSet(this, DbStudentSet) as EntitySet<E>;
                handled = true;
            }
            else if (typeof(E) == typeof(Entities.App.StudentResponse))
            {
                entitySet = new DataContext.App.StudentResponseSet(this, DbStudentResponseSet) as EntitySet<E>;
                handled = true;
            }
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetGeneratorViewSet<E>(ref ViewSet<E>? viewSet, ref bool handled) where E : Entities.ViewObject, new()
        {
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        static partial void OnViewModelCreating(ModelBuilder modelBuilder)
        {
        }
        #endregion partial methods
    }
}
