//@CustomCode
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace programming_trainer.Logic.Entities.App
{
    /// <summary>
    /// Represents a learning assignment/task for students.
    /// Can be used for any learning topic (programming, math, languages, etc.).
    /// </summary>
    [Table("Assignment")]
    [Index(nameof(StudentId), nameof(CategoryId), Name = "Assignment_Student_Category_Index")]
    public partial class Assignment : EntityObject
    {
        #region properties

        /// <summary>
        /// ID of the student who receives this assignment.
        /// </summary>
        [ForeignKey(nameof(Student))]
        public IdType StudentId { get; set; }

        /// <summary>
        /// The original prompt/request from the student describing what they want to learn.
        /// </summary>
        [MaxLength(500)]
        [Required]
        public string StudentPrompt { get; set; } = string.Empty;

        /// <summary>
        /// ID of the category/topic this assignment belongs to.
        /// </summary>
        [ForeignKey(nameof(Category))]
        public IdType CategoryId { get; set; }

        /// <summary>
        /// Title of the assignment.
        /// </summary>
        [MaxLength(100)]
        [Required]
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Detailed description of the assignment/task.
        /// Generated by AI based on student prompt.
        /// </summary>
        [Required]
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Current status of the assignment.
        /// Possible values: "Created", "InProgress", "Completed"
        /// </summary>
        [MaxLength(50)]
        [Required]
        public string Status { get; set; } = "Created";

        /// <summary>
        /// Date and time when the assignment was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        #endregion properties

        #region navigation properties

        /// <summary>
        /// Navigation property to the student who owns this assignment.
        /// </summary>
        public Student? Student { get; set; }

        /// <summary>
        /// Navigation property to the category this assignment belongs to.
        /// </summary>
        public programming_trainer.Logic.Entities.Data.Category? Category { get; set; }

        /// <summary>
        /// Collection of student responses/submissions for this assignment.
        /// A student can submit multiple attempts (1:n relationship).
        /// </summary>
        public List<StudentResponse> StudentResponses { get; set; } = [];

        #endregion navigation properties

        #region constructor

        public Assignment()
        {
            CreatedDate = DateTime.UtcNow;
        }

        #endregion constructor

        #region overrides

        public override string ToString()
        {
            return $"{Title} - {Status} ({StudentPrompt})";
        }

        #endregion overrides
    }
}
